### PR TITLE
update README.md

### PR DESCRIPTION
**Pull request by voodoologic**
This is the way I got the module to work.

### CODE REVIEW

**Comment by voodoologic** [comment]
The readme busted the app?  Impressive!

**Comment by coopergillan** [comment]
@voodoologic - I think it was actually the change to `lib/runbook/version.rb` in 3732d630b8a3fc29af31f8df4580610955285b7f. I raised #41.

**Comment by coopergillan** [comment]
@voodoologic - the build on `master` has now been fixed. A rebase should take care of the build failure here.

**Review by pblesi — APPROVED** [review]

**Review by coopergillan — APPROVED** [review]
👍

**Pull request merged**
