### PR TITLE
GH-41 - Remove install method per deprecation warnings

### PR DESCRIPTION
**Pull request by coopergillan**
### What

* Remove `install` in favor of `init`
* Fix an unnamed constant message in the `lib/runbook` module
* Prepare `CHANGELOG` for bug fix version bump and fix typo

### Why

* The method was marked for deprecation in `v1.0.0` but did not get removed when the version was tagged
* This allows the specs to pass

### A note on the CHANGELOG

There is no date here for `v1.0.1`, so that can be added when it the time comes to tag the next version.

Relates to #41

@pblesi

### CODE REVIEW

**Review by pblesi — APPROVED** [review]
The changes look good. The failure is likely due to this: https://www.docker.com/increase-rate-limit

You can try kicking the build to get it to pass, otherwise it is highly likely that the failure is related to the changes.

**Comment by coopergillan** [comment]
@pblesi - awesome, thanks for the tip. Kicked it again and it looks good now.

**Comment by coopergillan** [comment]
@pblesi - also, I'm not able to merge this one, ha 😅

**Comment by coopergillan** [comment]
@pblesi - holding off on updating the change log until the new version is ready to be published. Left the commit in for reference though.

**Pull request merged**
